# Generated by Django 4.0.5 on 2023-02-03 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_todo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("image_url", models.URLField()),
                ("description", models.CharField(max_length=312)),
                ("quantity", models.IntegerField()),
                ("price", models.FloatField()),
            ],
        ),
    ]
